### PR TITLE
Update gamescope to 3.14.1 and 4 modules, fix glm

### PR DESCRIPTION
**Pull request by ColinKinloch**
Update hwdata-0.378.tar.gz to 0.379
Update libavif.git to 1.0.4
Update glm-0.9.9.8.tar.gz to 1.0.0
Update gamescope.git to 3.14.1

### CODE REVIEW

**Comment by ColinKinloch** [comment]
bot, build org.freedesktop.Platform.VulkanLayer.gamescope

**Comment by ColinKinloch** [comment]
The external data checkers on the fritz again, @orowith2os

**Comment by orowith2os** [comment]
womp womp

**Comment by orowith2os** [comment]
At this point, just ask Bart to give you maintainer permissions - I have no problems with it, and you've done far more lately than me.

**Pull request merged**
